export type Problem = {
  id: string;
  title: string;
  topic: string;
  pattern: string;
  spec: string;
  /** progressive hints: restate → trace → plan */
  hints: string[];
  plan: string;
  /** correct code, top to bottom, indentation included */
  solution: string[];
  distractors: { t: string; why: string }[];
};

export const PROBLEMS: Problem[] = [
  {
    id: "max",
    title: "Largest element of an array",
    topic: "Arrays",
    pattern: "Running best",
    spec: "Write maxFor(int[] numbers): return the largest value. The array has at least one element and may contain negative numbers.",
    hints: [
      "Restate: input int[], output the biggest int. Smallest legal input has 1 element. What should the answer be then?",
      "By hand on {-5, -2, -9}: you keep 'the biggest so far'. What is it before you look at anything? It must be a real element.",
      "Plan: best = first element; for every remaining element, if it beats best, replace best; return best.",
    ],
    plan: "best = numbers[0]\nfor i from 1 to length-1:\n    if numbers[i] > best: best = numbers[i]\nreturn best",
    solution: [
      "public static int maxFor(int[] numbers) {",
      "    int best = numbers[0];",
      "    for (int i = 1; i < numbers.length; i++) {",
      "        if (numbers[i] > best) {",
      "            best = numbers[i];",
      "        }",
      "    }",
      "    return best;",
      "}",
    ],
    distractors: [
      { t: "    int best = 0;", why: "If every number is negative, 0 would wrongly win: 0 isn't in the array." },
      { t: "    for (int i = 1; i <= numbers.length; i++) {", why: "<= reads numbers[length], one past the end: ArrayIndexOutOfBoundsException." },
      { t: "        if (numbers[i] < best) {", why: "This finds the minimum, not the maximum." },
    ],
  },
  {
    id: "reverse",
    title: "Reverse an array in place",
    topic: "Arrays",
    pattern: "Two indices from the ends + swap",
    spec: "Write reverse(int[] a) that reverses the array in place (no new array).",
    hints: [
      "Restate: void, mutates a. For {1,2,3,4} the result is {4,3,2,1}.",
      "By hand: swap the first and last, then the second and second-to-last… When do you stop? (When the two positions meet in the middle.)",
      "Plan: lo = 0, hi = length-1; while lo < hi swap a[lo] and a[hi], then move both inward. A swap needs a temporary variable.",
    ],
    plan: "lo = 0; hi = length-1\nwhile lo < hi:\n    tmp = a[lo]; a[lo] = a[hi]; a[hi] = tmp\n    lo++; hi--",
    solution: [
      "public static void reverse(int[] a) {",
      "    int lo = 0;",
      "    int hi = a.length - 1;",
      "    while (lo < hi) {",
      "        int tmp = a[lo];",
      "        a[lo] = a[hi];",
      "        a[hi] = tmp;",
      "        lo++;",
      "        hi--;",
      "    }",
      "}",
    ],
    distractors: [
      { t: "    int hi = a.length;", why: "a[a.length] is out of bounds; the last index is length - 1." },
      { t: "        a[hi] = a[lo];", why: "Without saving a[lo] first, a[lo] is overwritten and both cells end up equal (the classic bad swap)." },
      { t: "    while (lo > hi) {", why: "lo starts smaller than hi, so this loop would never run." },
    ],
  },
  {
    id: "copy",
    title: "Copy an array manually",
    topic: "Arrays",
    pattern: "Build a new copy",
    spec: "Write copyOf(int[] a) returning a NEW array with the same contents (don't use Arrays.copyOf).",
    hints: [
      "Restate: return type int[]; the result must be a different array object, not an alias.",
      "By hand: make an empty array of the same length, then move over each element by index.",
      "Plan: allocate b with a.length; for every i set b[i] = a[i]; return b.",
    ],
    plan: "b = new int[a.length]\nfor i in 0..length-1: b[i] = a[i]\nreturn b",
    solution: [
      "public static int[] copyOf(int[] a) {",
      "    int[] b = new int[a.length];",
      "    for (int i = 0; i < a.length; i++) {",
      "        b[i] = a[i];",
      "    }",
      "    return b;",
      "}",
    ],
    distractors: [
      { t: "    int[] b = a;", why: "That copies the arrow: b and a are the same array (an alias), not a copy." },
      { t: "    for (int i = 0; i < b.length - 1; i++) {", why: "Stops one short: the last element is never copied." },
    ],
  },
  {
    id: "window",
    title: "windowPosSum",
    topic: "Arrays",
    pattern: "Scan with index + accumulator (nested)",
    spec: "For each positive a[i], replace it with a[i] + … + a[i+n] (stop at the end of the array). Non-positive cells are left alone. Modify a in place.",
    hints: [
      "Restate: void, in place. What if i + n runs past the end?",
      "By hand on {1,2,-3,4} with n = 2: a[0] becomes 1+2+(-3) = 0, and so on. Which values does the window use: original or already changed?",
      "Plan: for each i left to right; if a[i] > 0: end = min(i+n, last index); sum a[i..end]; store in a[i].",
    ],
    plan: "for i in 0..length-1:\n    if a[i] > 0:\n        end = min(i + n, length - 1)\n        sum = a[i] + ... + a[end]\n        a[i] = sum",
    solution: [
      "public static void windowPosSum(int[] a, int n) {",
      "    for (int i = 0; i < a.length; i++) {",
      "        if (a[i] > 0) {",
      "            int end = Math.min(i + n, a.length - 1);",
      "            int sum = 0;",
      "            for (int j = i; j <= end; j++) {",
      "                sum += a[j];",
      "            }",
      "            a[i] = sum;",
      "        }",
      "    }",
      "}",
    ],
    distractors: [
      { t: "            int end = i + n;", why: "Can exceed a.length - 1, giving ArrayIndexOutOfBoundsException near the end." },
      { t: "            for (int j = i; j < end; j++) {", why: "< end leaves out a[end]. The window is inclusive (a[i] through a[i+n])." },
      { t: "                a[i] += a[j];", why: "Modifying a[i] while summing double-counts a[i] (it is in its own window)." },
    ],
  },
  {
    id: "tri",
    title: "Triangular 2D array",
    topic: "Arrays",
    pattern: "Build a new structure row by row",
    spec: "Write makeTri(n) returning a jagged array with n rows where row i has i+1 entries 0, 1, …, i.",
    hints: [
      "Restate: return int[][]; rows have different lengths so you can't use new int[n][n].",
      "By hand for n = 3: {{0},{0,1},{0,1,2}}. Row i has length i+1.",
      "Plan: create the outer array with n empty rows; for each i create row i with the right length, then fill j from 0..i.",
    ],
    plan: "tri = new int[n][]\nfor i in 0..n-1:\n    tri[i] = new int[i+1]\n    for j in 0..i: tri[i][j] = j\nreturn tri",
    solution: [
      "public static int[][] makeTri(int n) {",
      "    int[][] tri = new int[n][];",
      "    for (int i = 0; i < n; ++i) {",
      "        tri[i] = new int[i + 1];",
      "        for (int j = 0; j <= i; ++j) {",
      "            tri[i][j] = j;",
      "        }",
      "    }",
      "    return tri;",
      "}",
    ],
    distractors: [
      { t: "    int[][] tri = new int[n][n];", why: "That makes a square grid: every row has length n." },
      { t: "        for (int j = 0; j < i; ++j) {", why: "< i gives only i entries; row i needs i + 1." },
    ],
  },
  {
    id: "isize",
    title: "iterativeSize on IntNode",
    topic: "Linked lists",
    pattern: "Walk a pointer",
    spec: "Inside class IntNode, write int iterativeSize() that counts the nodes from this to the end.",
    hints: [
      "Restate: instance method; returns an int; smallest list is one node (this).",
      "By hand: put your finger on the first node, count it, slide to the next; stop when you fall off the end.",
      "Plan: current = this; count = 0; while current != null: count++, current = current.next.",
    ],
    plan: "current = this; total = 0\nwhile current != null:\n    total++\n    current = current.next\nreturn total",
    solution: [
      "public int iterativeSize() {",
      "    IntNode current = this;",
      "    int totalSize = 0;",
      "    while (current != null) {",
      "        totalSize++;",
      "        current = current.next;",
      "    }",
      "    return totalSize;",
      "}",
    ],
    distractors: [
      { t: "    while (current.next != null) {", why: "This stops ON the last node, so the last node is never counted (off by one)." },
      { t: "    int totalSize = 1;", why: "Starting at 1 and also counting each node inside the loop double-counts." },
      { t: "        this = this.next;", why: "You can't assign to `this`. Use a separate variable to walk." },
    ],
  },
  {
    id: "get",
    title: "get(i) on IntNode",
    topic: "Linked lists",
    pattern: "Walk a fixed number of hops",
    spec: "Inside IntNode, write int get(int i) returning the i-th item (0 is this). Assume i is valid.",
    hints: [
      "Restate: index 0 is the first node. What should get(0) do? (No hops.)",
      "By hand: to reach index 2 you hop twice from the front.",
      "Plan: current = this; repeat i times: current = current.next; return current.head.",
    ],
    plan: "current = this\nrepeat i times: current = current.next\nreturn current.head",
    solution: [
      "public int get(int i) {",
      "    IntNode current = this;",
      "    while (i > 0) {",
      "        current = current.next;",
      "        i--;",
      "    }",
      "    return current.head;",
      "}",
    ],
    distractors: [
      { t: "    while (i >= 0) {", why: "Hops i + 1 times, landing one node too far (or past the end)." },
      { t: "    return current.next.head;", why: "After i hops, current is already the target. .next would give the item after it." },
      { t: "        i++;", why: "i would grow forever: this loop never ends." },
    ],
  },
  {
    id: "addlast-intnode",
    title: "addLast on IntNode",
    topic: "Linked lists",
    pattern: "Walk to the LAST node (current.next != null)",
    spec: "Inside IntNode, write void addLast(int x) that appends a new node holding x at the end of the chain that starts at this.",
    hints: [
      "Restate: mutates the chain; the new node's next is null. You must change the LAST node's next.",
      "By hand: walk until you're standing ON the last node (its next is null), then attach.",
      "Plan: current = this; while current.next != null: advance; current.next = new IntNode(x, null).",
    ],
    plan: "current = this\nwhile current.next != null: current = current.next\ncurrent.next = new IntNode(x, null)",
    solution: [
      "public void addLast(int x) {",
      "    IntNode current = this;",
      "    while (current.next != null) {",
      "        current = current.next;",
      "    }",
      "    current.next = new IntNode(x, null);",
      "}",
    ],
    distractors: [
      { t: "    while (current != null) {", why: "Ends when current is null, then current.next throws NullPointerException." },
      { t: "    current = new IntNode(x, null);", why: "That only re-points the local variable; the chain is not changed." },
    ],
  },
  {
    id: "rsize",
    title: "Recursive size on IntNode",
    topic: "Linked lists",
    pattern: "Recurse on the rest",
    spec: "Inside IntNode, write int size() recursively (no loops).",
    hints: [
      "Restate: a list is one node plus a smaller list.",
      "What is the smallest list? One node (next == null). Its size is 1.",
      "Plan: if next is null return 1; otherwise 1 + size of the rest.",
    ],
    plan: "if next == null: return 1\nreturn 1 + next.size()",
    solution: [
      "public int size() {",
      "    if (this.next == null) {",
      "        return 1;",
      "    }",
      "    return 1 + this.next.size();",
      "}",
    ],
    distractors: [
      { t: "    if (this == null) {", why: "`this` is never null inside an instance method, so the base case would never trigger." },
      { t: "    return this.next.size();", why: "Forgets to count this node." },
    ],
  },
  {
    id: "addfirst",
    title: "SLList.addFirst (sentinel)",
    topic: "Sentinel SLList",
    pattern: "Rewire arrows in the right order",
    spec: "In SLList (fields: IntNode sentinel; int size), write addFirst(int x).",
    hints: [
      "Restate: the new node goes right after the sentinel. size must be updated.",
      "Draw sentinel → A → B. The new node must point to A first, then the sentinel points to the new node.",
      "Plan: sentinel.next = new IntNode(x, sentinel.next) reads the old arrow before overwriting it. Then size++.",
    ],
    plan: "sentinel.next = new IntNode(x, sentinel.next)\nsize++",
    solution: [
      "public void addFirst(int x) {",
      "    sentinel.next = new IntNode(x, sentinel.next);",
      "    size++;",
      "}",
    ],
    distractors: [
      { t: "    sentinel.next = new IntNode(x, null);", why: "Throws away the rest of the list: the old first node is lost." },
      { t: "    sentinel = new IntNode(x, sentinel);", why: "Replaces the sentinel with real data; the sentinel must stay the dummy node." },
    ],
  },
  {
    id: "removefirst",
    title: "SLList.removeFirst (sentinel)",
    topic: "Sentinel SLList",
    pattern: "Skip over a node + guard the empty case",
    spec: "Write removeFirst(): remove the front item; do nothing if the list is empty. Keep size correct.",
    hints: [
      "Restate: what if the list is empty? sentinel.next is null there.",
      "Draw sentinel → A → B. After removal: sentinel → B. Which single arrow changes?",
      "Plan: if size == 0 return. sentinel.next = sentinel.next.next; size--.",
    ],
    plan: "if size == 0: return\nsentinel.next = sentinel.next.next\nsize--",
    solution: [
      "public void removeFirst() {",
      "    if (size == 0) {",
      "        return;",
      "    }",
      "    sentinel.next = sentinel.next.next;",
      "    size--;",
      "}",
    ],
    distractors: [
      { t: "    sentinel = sentinel.next;", why: "The sentinel would become a real node; the dummy first node is lost." },
      { t: "    sentinel.next = null;", why: "Removes everything, not just the first item." },
    ],
  },
  {
    id: "insert",
    title: "SLList.insert(x, k)",
    topic: "Sentinel SLList",
    pattern: "Walk to the node BEFORE, then splice",
    spec: "Write insert(int x, int k): put x at position k (0 = front). If k is beyond the end, append.",
    hints: [
      "Restate: inserting at position k means finding the node just before position k. For k = 0 that is the sentinel.",
      "By hand: start p at the sentinel; hop k times (but stop early if you run out of nodes).",
      "Plan: p = sentinel; while k > 0 and p.next != null: hop, k--. Then p.next = new IntNode(x, p.next); size++.",
    ],
    plan: "p = sentinel\nwhile k > 0 and p.next != null: p = p.next; k--\np.next = new IntNode(x, p.next)\nsize++",
    solution: [
      "public void insert(int x, int k) {",
      "    IntNode p = sentinel;",
      "    while (k > 0 && p.next != null) {",
      "        p = p.next;",
      "        k--;",
      "    }",
      "    p.next = new IntNode(x, p.next);",
      "    size++;",
      "}",
    ],
    distractors: [
      { t: "    IntNode p = sentinel.next;", why: "Starting past the sentinel makes k = 0 (insert at front) impossible." },
      { t: "    p.next = new IntNode(x, null);", why: "Drops everything after p." },
    ],
  },
  {
    id: "alist-add",
    title: "AList.addLast with resizing",
    topic: "ArrayList",
    pattern: "Grow when full, then store at size",
    spec: "AList<T> has T[] items and int size. Write addLast(T x) that doubles the array when it is full. Assume a helper resize(int newCapacity) exists.",
    hints: [
      "Restate: when is the array full? (size == items.length)",
      "Order matters: make room first, then store.",
      "Plan: if full, resize to twice the capacity; items[size] = x; size++.",
    ],
    plan: "if size == items.length: resize(2 * size)\nitems[size] = x\nsize++",
    solution: [
      "public void addLast(T x) {",
      "    if (size == items.length) {",
      "        resize(size * 2);",
      "    }",
      "    items[size] = x;",
      "    size++;",
      "}",
    ],
    distractors: [
      { t: "    items[size + 1] = x;", why: "The next free slot is items[size], not size + 1." },
      { t: "        resize(size + 1);", why: "Growing by +1 makes every add copy everything (about n² total copying)." },
    ],
  },
  {
    id: "alist-remove",
    title: "AList.removeLast",
    topic: "ArrayList",
    pattern: "Save, clear the slot (GC), shrink size",
    spec: "Write T removeLast() for AList<T>: remove and return the last item (assume non-empty). Avoid loitering references.",
    hints: [
      "Restate: last item is at index size - 1.",
      "You must return the item AFTER clearing the slot, so save it first.",
      "Plan: T item = items[size-1]; items[size-1] = null; size--; return item.",
    ],
    plan: "item = items[size - 1]\nitems[size - 1] = null\nsize--\nreturn item",
    solution: [
      "public T removeLast() {",
      "    T itemToRemove = items[size - 1];",
      "    items[size - 1] = null;",
      "    size--;",
      "    return itemToRemove;",
      "}",
    ],
    distractors: [
      { t: "    T itemToRemove = items[size];", why: "items[size] is the empty slot beyond the last item (null)." },
      { t: "    return items[size - 1];", why: "By the time this line runs the slot has been set to null and size decreased, so it would not return the removed item. Save it in a variable first." },
    ],
  },
  {
    id: "count-char",
    title: "Count a letter in each String",
    topic: "Arrays",
    pattern: "Array of tallies + nested loops",
    spec: "Write countI(String[] words): return an int[] whose j-th entry is how many lowercase 'i' characters are in words[j]. Example: {\"iRS\", \"mini\", \"I1iI1\"} gives {1, 2, 1}.",
    hints: [
      "Restate: input String[], output int[] of the SAME length: one tally per word.",
      "By hand on {\"mini\"}: look at m, i, n, i. Two are 'i', so the tally for that word is 2. You need a loop over words and, inside it, a loop over characters.",
      "Plan: counts = new int[words.length]; for each word k: for each char j: if it is 'i', counts[k]++; return counts.",
    ],
    plan: "counts = new int[words.length]\nfor k over words:\n    st = words[k]\n    for j over st:\n        if st.charAt(j) == 'i': counts[k]++\nreturn counts",
    solution: [
      "public static int[] countI(String[] words) {",
      "    int[] counts = new int[words.length];",
      "    for (int k = 0; k < words.length; k++) {",
      "        String st = words[k];",
      "        for (int j = 0; j < st.length(); j++) {",
      "            if (st.charAt(j) == 'i') {",
      "                counts[k]++;",
      "            }",
      "        }",
      "    }",
      "    return counts;",
      "}",
    ],
    distractors: [
      { t: "    int[] counts = new int[st.length()];", why: "There is one tally per WORD, so the size is words.length (and st does not exist yet)." },
      { t: "            if (st.charAt(j) == \"i\") {", why: "charAt gives a char: compare with single quotes 'i'. \"i\" is a String and will not compile." },
      { t: "                counts[j]++;", why: "j walks the characters. The tally belongs to the word, so it is counts[k]." },
      { t: "        for (int j = 0; j < st.length; j++) {", why: "A String has length() with parentheses. Only arrays use .length." },
    ],
  },
  {
    id: "sl-count",
    title: "SLList.count(target) with a sentinel",
    topic: "Sentinel SLList",
    pattern: "Walk a pointer from sen.next",
    spec: "In a sentinel list of Strings (field sen; StrNode has String head and StrNode next), write int count(String target): how many nodes hold target. Walk once; do not modify the list.",
    hints: [
      "Restate: the real data starts at sen.next. What is the answer for an empty list? (0, and the loop must simply not run.)",
      "By hand on a, b, a with target a: put a finger on the first real node, tally if it matches, slide on, stop when you fall off the end (null).",
      "Plan: c = 0; p = sen.next; while p != null: if p.head.equals(target) c++; p = p.next. Return c.",
    ],
    plan: "c = 0\np = sen.next\nwhile p != null:\n    if p.head.equals(target): c++\n    p = p.next\nreturn c",
    solution: [
      "public int count(String target) {",
      "    int c = 0;",
      "    StrNode p = sen.next;",
      "    while (p != null) {",
      "        if (p.head.equals(target)) {",
      "            c++;",
      "        }",
      "        p = p.next;",
      "    }",
      "    return c;",
      "}",
    ],
    distractors: [
      { t: "    StrNode p = sen;", why: "Starting at the sentinel also reads its dummy String, which is not part of the list." },
      { t: "    while (p.next != null) {", why: "Stops ON the last node so it is never counted, and crashes (null.next) on an empty list. Test p != null." },
      { t: "        if (p.head == target) {", why: "== compares references. Equal Strings can be different objects; use .equals." },
      { t: "    int c = 1;", why: "The count starts at 0. Starting at 1 over-counts by one." },
    ],
  },
  {
    id: "sl-removeall",
    title: "SLList.removeAll(target) (hard)",
    topic: "Sentinel SLList",
    pattern: "Trail one node behind, unlink without advancing",
    spec: "In the sentinel list of Strings, write void removeAll(String target): remove EVERY node whose data equals target, in a single pass. If none match, nothing changes.",
    hints: [
      "Restate: to delete a node you must change the arrow of the node BEFORE it. The first real node's predecessor is the sentinel, which is why we start there.",
      "By hand on a, a, b with target a: after unlinking the first a, the next node is ANOTHER a. If you step forward right after unlinking you would skip it.",
      "Plan: prev = sen; while prev.next != null: if prev.next matches, prev.next = prev.next.next (do not move); else prev = prev.next.",
    ],
    plan: "prev = sen\nwhile prev.next != null:\n    if prev.next.head.equals(target):\n        prev.next = prev.next.next   # unlink, stay put\n    else:\n        prev = prev.next",
    solution: [
      "public void removeAll(String target) {",
      "    StrNode prev = sen;",
      "    while (prev.next != null) {",
      "        if (prev.next.head.equals(target)) {",
      "            prev.next = prev.next.next;",
      "        } else {",
      "            prev = prev.next;",
      "        }",
      "    }",
      "}",
    ],
    distractors: [
      { t: "    StrNode prev = sen.next;", why: "Then you can never remove the first real node: its predecessor is the sentinel." },
      { t: "    while (prev != null) {", why: "At the last node prev.next is null and prev.next.head throws a NullPointerException. Test prev.next != null." },
      { t: "        if (prev.next.head == target) {", why: "== compares references; use .equals for Strings." },
      { t: "            prev.next = null;", why: "Cuts off the whole rest of the list, not just this node." },
    ],
  },
];
