import type { Topic } from "./lessons";

export type Q = {
  id: string;
  topic: Topic;
  level: 1 | 2 | 3;
  q: string;
  code?: string;
} & (
  | { kind: "mcq"; options: string[]; answer: number; why: string }
  | { kind: "type"; answer: string; why: string; placeholder?: string }
);

/** normalise typed answers: strip brackets/commas, collapse spaces, lowercase */
export const norm = (s: string) =>
  s
    .toLowerCase()
    .replace(/[\[\]{}(),]+/g, " ")
    .trim()
    .split(/\s+/)
    .join(" ");

export const QUESTIONS: Q[] = [
  /* ---------------- Java basics ---------------- */
  { id: "jb1", topic: "Java basics", level: 1, kind: "mcq", q: "What does this print?", code: `System.out.println(10 / 4);`, options: ["2.5", "2", "3", "2.0"], answer: 1, why: "int / int is integer division: the fraction is discarded. 10 / 4.0 would be 2.5." },
  { id: "jb2", topic: "Java basics", level: 1, kind: "mcq", q: "What is x at the end?", code: `int x = 7;\nx += 3;\nx++;`, options: ["10", "11", "12", "8"], answer: 1, why: "7 + 3 = 10, then x++ makes 11." },
  { id: "jb3", topic: "Java basics", level: 2, kind: "type", q: "What is printed? (System.out.print, no newlines)", code: `for (int i = 1; i <= 3; i++) {\n    for (int j = 1; j <= i; j++) {\n        System.out.print(j);\n    }\n}`, answer: "112123", placeholder: "digits only", why: "i=1 prints 1; i=2 prints 12; i=3 prints 123. Together: 112123." },
  { id: "jb4", topic: "Java basics", level: 2, kind: "mcq", q: "Which is the Java equivalent of Python's `for x in a:` where a is an int[]?", options: ["for (x : a)", "for (int x : a)", "for (int x in a)", "foreach (int x : a)"], answer: 1, why: "The for-each loop needs the element type: `for (int x : a)`." },
  { id: "jb5", topic: "Java basics", level: 2, kind: "mcq", q: "Which is correct for getting lengths?", options: ["array: a.length()  string: s.length", "array: a.length  string: s.length()", "array: a.size()  string: s.size()", "array: len(a)  string: len(s)"], answer: 1, why: "Arrays have a length field (no parentheses); Strings have a length() method." },
  { id: "jb6", topic: "Java basics", level: 2, kind: "mcq", q: "What does this print?", code: `String a = new String("hi");\nString b = new String("hi");\nSystem.out.println((a == b) + \" \" + a.equals(b));`, options: ["true true", "false true", "true false", "false false"], answer: 1, why: "== on references compares arrows (are they the same object?). Two `new` calls make two objects. equals compares the contents." },
  { id: "jb7", topic: "Java basics", level: 3, kind: "mcq", q: "What happens?", code: `for (int i = 0; i < 3; i++) { }\nSystem.out.println(i);`, options: ["prints 3", "prints 2", "compile error: i is out of scope", "prints 0"], answer: 2, why: "A variable declared in the for-header only exists inside the loop." },

  /* ---------------- Arrays ---------------- */
  { id: "ar1", topic: "Arrays", level: 1, kind: "mcq", q: "What happens?", code: `int[] a = {1, 2, 3};\nSystem.out.println(a[a.length]);`, options: ["prints 3", "prints 0", "ArrayIndexOutOfBoundsException", "compile error"], answer: 2, why: "Valid indices are 0..length-1. a[length] is one past the end (a runtime exception, not a compile error)." },
  { id: "ar2", topic: "Arrays", level: 2, kind: "type", q: "What are the contents of a afterwards? Write like: 1 2 3", code: `int[] a = {2, 4, 6};\nfor (int i = 0; i < a.length; i++) {\n    a[i] = a[i] * 2;\n}`, answer: "4 8 12", why: "Each cell is doubled in place: 4, 8, 12." },
  { id: "ar3", topic: "Arrays", level: 2, kind: "mcq", q: "For `int[][] g = new int[3][4];` what is g[0].length?", options: ["3", "4", "12", "0"], answer: 1, why: "g has 3 rows; each row is an int[4]. g.length is 3, g[0].length is 4." },
  { id: "ar4", topic: "Arrays", level: 3, kind: "mcq", q: "What happens?", code: `int[][] t = new int[3][];\nt[0][0] = 1;`, options: ["Works: t[0][0] is 1", "NullPointerException: row t[0] was never created", "ArrayIndexOutOfBoundsException", "Compile error"], answer: 1, why: "`new int[3][]` makes 3 empty row slots holding null. You must create each row (`t[0] = new int[2]`) first." },
  { id: "ar5", topic: "Arrays", level: 2, kind: "mcq", q: "What is the bug?", code: `int sum = 0;\nfor (int i = 0; i <= a.length; i++) {\n    sum += a[i];\n}`, options: ["No bug", "i <= a.length reads one element past the end", "sum should start at 1", "Should be i < a.length - 1"], answer: 1, why: "The last valid index is a.length - 1. Use i < a.length." },
  { id: "ar6", topic: "Arrays", level: 3, kind: "type", q: "What is a after windowPosSum(a, 1)? (Each positive a[i] becomes a[i] + a[i+1], if it exists.)", code: `int[] a = {3, -1, 2};\nwindowPosSum(a, 1);`, answer: "2 -1 2", why: "a[0]=3 is positive: 3 + (-1) = 2. a[1] is negative: unchanged. a[2]=2 is positive but has no right neighbour: just 2." },
  { id: "ar7", topic: "Arrays", level: 1, kind: "mcq", q: "What is z[2]?", code: `int[] z = new int[4];`, options: ["null", "0", "garbage", "compile error"], answer: 1, why: "New int arrays are zero-filled." },

  /* ---------------- References ---------------- */
  { id: "rf1", topic: "References", level: 1, kind: "mcq", q: "What is printed?", code: `static void inc(int x) { x++; }\n// main\nint n = 5;\ninc(n);\nSystem.out.println(n);`, options: ["5", "6", "0", "compile error"], answer: 0, why: "The parameter is a copy of the number 5; incrementing the copy doesn't affect n." },
  { id: "rf2", topic: "References", level: 2, kind: "mcq", q: "What does main print?", code: `static void zero(int[] arr) {\n    for (int i = 0; i < arr.length; i++) arr[i] = 0;\n}\n// main\nint[] d = {4, 5};\nzero(d);\nSystem.out.println(d[0] + d[1]);`, options: ["9", "0", "45", "compile error"], answer: 1, why: "arr is a copy of the arrow, so writing through it changes the shared array. d becomes {0, 0}." },
  { id: "rf3", topic: "References", level: 2, kind: "type", q: "What is printed? (two numbers)", code: `Point p = new Point(1, 2);   // fields x, y\nPoint q = p;\nq.x = 10;\nPoint r = new Point(1, 2);\nSystem.out.println(p.x + \" \" + r.x);`, answer: "10 1", why: "q is an alias of p, so q.x = 10 changes p's object. r is a separate object, still 1." },
  { id: "rf4", topic: "References", level: 1, kind: "mcq", q: "What happens?", code: `Dog d = null;\nd.bark();`, options: ["prints nothing", "NullPointerException", "compile error", "creates a Dog"], answer: 1, why: "Following a null arrow at runtime throws NullPointerException." },
  { id: "rf5", topic: "References", level: 2, kind: "mcq", q: "How many objects exist after this?", code: `Node a = new Node(1, null);\nNode b = new Node(2, a);\nNode c = b;`, options: ["1", "2", "3", "0"], answer: 1, why: "Only `new` makes objects: two. c is just another arrow to b's object." },
  { id: "rf6", topic: "References", level: 2, kind: "mcq", q: "Which describes `y = x;` when x and y are both Feline references?", options: ["Creates a new Feline copy for y", "Copies the arrow, so x and y point to the same object", "Copies the fields one by one", "Compile error"], answer: 1, why: "The Rule of Equals: = copies the bits in x's box. For references, those bits are an arrow." },
  { id: "rf7", topic: "References", level: 3, kind: "mcq", q: "After swap returns, what are a.w and b.w?", code: `static void swap(Feline p, Feline q) {\n    Feline t = p; p = q; q = t;\n}\n// main: a.w == 1, b.w == 2\nswap(a, b);`, options: ["2 and 1", "1 and 2", "1 and 1", "2 and 2"], answer: 1, why: "swap only exchanges its local copies of the arrows. main's a and b still point where they did." },
  { id: "rf8", topic: "References", level: 3, kind: "mcq", q: "What is the length of arr in main afterwards?", code: `static void reset(int[] x) {\n    x = new int[1];\n}\n// main\nint[] arr = new int[5];\nreset(arr);`, options: ["1", "5", "0", "compile error"], answer: 1, why: "`x = new int[1]` re-points only the local copy. main's arr still refers to the length-5 array." },

  /* ---------------- Overloading & static ---------------- */
  { id: "os1", topic: "Overloading & static", level: 1, kind: "mcq", q: "Which is part of a method's signature?", options: ["name and return type", "name and parameter types", "parameter names and return type", "only the name"], answer: 1, why: "Signature = name + parameter types (in order)." },
  { id: "os2", topic: "Overloading & static", level: 2, kind: "mcq", q: "Given only `void f(double x)` exists, what does `f(3)` do?", options: ["compile error", "calls f(double): the int widens to double", "calls f(int) automatically created", "runtime exception"], answer: 1, why: "An int can be widened to a double, so it compiles and calls f(double)." },
  { id: "os3", topic: "Overloading & static", level: 2, kind: "mcq", q: "Given only `void f(int x)` exists, what does `f(3.0)` do?", options: ["calls f(int)", "compile error: a double doesn't fit an int without a cast", "prints 3", "calls f(double)"], answer: 1, why: "Narrowing double → int is not automatic in Java." },
  { id: "os4", topic: "Overloading & static", level: 2, kind: "type", q: "What is printed? (two numbers)", code: `class C {\n    static int n = 0;\n    int id;\n    C() { n++; id = n; }\n}\n// main\nnew C();\nnew C();\nC c = new C();\nSystem.out.println(c.id + \" \" + C.n);`, answer: "3 3", why: "n is shared and goes 1, 2, 3. The third object copies 3 into its own id." },
  { id: "os5", topic: "Overloading & static", level: 2, kind: "mcq", q: "Why does this fail to compile?", code: `public class A {\n    int count = 0;\n    void inc() { count++; }\n    public static void main(String[] args) {\n        inc();\n    }\n}`, options: ["inc is private", "main is static, so it can't call an instance method without an object", "count isn't initialized", "main must return int"], answer: 1, why: "A static method has no `this`. Create an object: `new A().inc()`." },
  { id: "os6", topic: "Overloading & static", level: 3, kind: "mcq", q: "Are these two methods legal in the same class?", code: `int m(int a)    { … }\nlong m(int b)   { … }`, options: ["Yes: return types differ", "Yes: parameter names differ", "No: same signature m(int)", "Only if one is static"], answer: 2, why: "Return type and parameter names aren't part of the signature, so this is a duplicate." },

  /* ---------------- Linked lists ---------------- */
  { id: "ll1", topic: "Linked lists", level: 1, kind: "mcq", q: "What is printed?", code: `IntNode L = new IntNode(1, new IntNode(2, new IntNode(3, null)));\nL = L.next;\nSystem.out.println(L.head);`, options: ["1", "2", "3", "null"], answer: 1, why: "L moves to the second node, whose head is 2." },
  { id: "ll2", topic: "Linked lists", level: 2, kind: "mcq", q: "For the list 1 → 2 → 3, what is `L.next.next.head`?", options: ["1", "2", "3", "NullPointerException"], answer: 2, why: "L.next is node 2; L.next.next is node 3; its head is 3." },
  { id: "ll3", topic: "Linked lists", level: 2, kind: "mcq", q: "For the list 1 → 2 → 3, what does `L.next.next.next.head` do?", options: ["returns 3", "returns 0", "NullPointerException", "compile error"], answer: 2, why: "L.next.next.next is null (past the last node); reading .head from null throws." },
  { id: "ll4", topic: "Linked lists", level: 3, kind: "mcq", q: "What happens when you call iterativeSize() on this list?", code: `IntNode a = new IntNode(1, null);\na.next = a;`, options: ["returns 1", "returns 2", "infinite loop: the chain never reaches null", "NullPointerException"], answer: 2, why: "a.next points back to a, so current never becomes null." },
  { id: "ll5", topic: "Linked lists", level: 2, kind: "mcq", q: "Which loop stops ON the last node of a non-empty chain?", options: ["while (cur != null)", "while (cur.next != null)", "while (cur.next == null)", "while (cur.head != 0)"], answer: 1, why: "cur.next != null keeps walking until cur.next is null, meaning cur is the last node." },
  { id: "ll6", topic: "Linked lists", level: 2, kind: "mcq", q: "What is the base case of a recursive size() on IntNode?", options: ["this == null", "this.next == null (a single node)", "head == 0", "size == 0"], answer: 1, why: "`this` is never null in an instance method. A one-node list (next == null) is the smallest list, and its size is 1." },
  { id: "ll7", topic: "Linked lists", level: 2, kind: "mcq", q: "L2 = L.incrList(1). Does L change?", options: ["Yes: every head is incremented", "No: incrList builds a brand new list", "Only the first node", "Only if L has one node"], answer: 1, why: "It returns new nodes. The original list is untouched." },
  { id: "ll8", topic: "Linked lists", level: 1, kind: "mcq", q: "How does the time for get(i) on a singly linked list behave?", options: ["Constant", "Grows with i (hops)", "Grows with i²", "Always the same as size()"], answer: 1, why: "You must hop from the front i times." },

  /* ---------------- Sentinel SLList ---------------- */
  { id: "sl1", topic: "Sentinel SLList", level: 2, kind: "type", q: "After these calls, list the items in order.", code: `SLList L = new SLList();\nL.addFirst(3);\nL.addLast(5);\nL.addFirst(1);\nL.insert(4, 2);\nL.removeFirst();`, answer: "3 4 5", placeholder: "e.g. 1 2 3", why: "[3] → [3,5] → [1,3,5] → insert 4 at position 2: [1,3,4,5] → removeFirst: [3,4,5]." },
  { id: "sl2", topic: "Sentinel SLList", level: 1, kind: "mcq", q: "What is sentinel.next in a brand-new empty SLList?", options: ["the sentinel itself", "null", "a node with head 0", "undefined"], answer: 1, why: "An empty list is just the sentinel with next = null." },
  { id: "sl3", topic: "Sentinel SLList", level: 2, kind: "mcq", q: "What does a sentinel node buy you?", options: ["Faster get(i)", "No special case for the first node / empty list", "Less memory", "Thread safety"], answer: 1, why: "Every real node has a predecessor, so insert/append code is uniform." },
  { id: "sl4", topic: "Sentinel SLList", level: 2, kind: "mcq", q: "Which line correctly adds x at the front?", options: ["sentinel = new IntNode(x, sentinel);", "sentinel.next = new IntNode(x, sentinel.next);", "sentinel.next = new IntNode(x, null);", "new IntNode(x, sentinel.next);"], answer: 1, why: "The new node must keep the old first node as its next, then sentinel.next is re-pointed to it." },
  { id: "sl5", topic: "Sentinel SLList", level: 2, kind: "mcq", q: "Why does SLList keep a `size` field?", options: ["It's required by Java", "So size() runs in constant time instead of walking the list", "To find the last node", "To avoid the sentinel"], answer: 1, why: "Every mutator updates it; size() just returns it." },
  { id: "sl6", topic: "Sentinel SLList", level: 3, kind: "mcq", q: "In a sentinel SLList with no `last` pointer, which operation is NOT constant time?", options: ["addFirst", "removeFirst", "addLast", "size"], answer: 2, why: "addLast must walk to the end." },
  { id: "sl7", topic: "Sentinel SLList", level: 3, kind: "mcq", q: "removeFirst on a list with exactly one item does what?", code: `sentinel.next = sentinel.next.next;\nsize--;`, options: ["sentinel.next becomes null and size 0", "NullPointerException", "size stays 1", "The sentinel is removed"], answer: 0, why: "sentinel.next is the only node; its next is null, so sentinel.next becomes null: empty list." },

  /* ---------------- Generics ---------------- */
  { id: "ge1", topic: "Generics", level: 1, kind: "mcq", q: "Which is legal?", options: ["SLList<int> a = new SLList<>();", "SLList<Integer> a = new SLList<>();", "SLList<integer> a = new SLList<>();", "SLList<> a = new SLList<Integer>;"], answer: 1, why: "Type arguments must be reference types; Integer is the wrapper of int." },
  { id: "ge2", topic: "Generics", level: 2, kind: "mcq", q: "What happens?", code: `SLList<Double> d = new SLList<>();\nd.addFirst(5);`, options: ["stores 5.0", "compile error: int can't be autoboxed to Double", "stores 5", "runtime exception"], answer: 1, why: "Autoboxing only wraps a primitive into its own wrapper: int → Integer. Use 5.0." },
  { id: "ge3", topic: "Generics", level: 2, kind: "mcq", q: "What is the wrapper type of `char`?", options: ["Char", "Character", "String", "Charable"], answer: 1, why: "char → Character (int → Integer, the others just capitalise)." },
  { id: "ge4", topic: "Generics", level: 3, kind: "mcq", q: "Why is `items = new T[8];` illegal, and what do we write instead?", options: ["T is too short; use `new TT[8]`", "Java can't create generic arrays; use `(T[]) new Object[8]`", "Arrays can't hold references", "It is legal"], answer: 1, why: "Generic array creation is disallowed. Create an Object[] and cast." },

  /* ---------------- Stacks & queues ---------------- */
  { id: "sq1", topic: "Stacks & queues", level: 2, kind: "type", q: "Push 4, push 5, pop, push 6, pop, pop. List the popped values in order.", answer: "5 6 4", placeholder: "e.g. 1 2 3", why: "LIFO: pop returns 5, then (after pushing 6) 6, then 4." },
  { id: "sq2", topic: "Stacks & queues", level: 2, kind: "type", q: "Enqueue 4, enqueue 5, dequeue, enqueue 6, dequeue, dequeue. List the dequeued values in order.", answer: "4 5 6", placeholder: "e.g. 1 2 3", why: "FIFO: they come out in arrival order 4, 5, 6." },
  { id: "sq3", topic: "Stacks & queues", level: 1, kind: "mcq", q: "Which ADT models a browser's Back button?", options: ["Queue", "Stack", "Array", "Sentinel"], answer: 1, why: "Back returns to the most recently visited page: LIFO." },
  { id: "sq4", topic: "Stacks & queues", level: 2, kind: "mcq", q: "Which of these bracket strings is balanced?", options: ["([)]", "{[()]}", "(()", "())("], answer: 1, why: "{[()]} nests properly. ([)] closes ) before ]; (() has an unmatched opener; ())( closes before opening." },
  { id: "sq5", topic: "Stacks & queues", level: 3, kind: "mcq", q: "To reverse a word, you push each letter then pop them all. Why does it work?", options: ["Stacks sort items", "LIFO returns the last letter first", "Queues are faster", "Popping copies the word"], answer: 1, why: "The last letter pushed is the first popped, so the order comes out reversed." },
  { id: "sq6", topic: "Stacks & queues", level: 2, kind: "mcq", q: "Implement a stack on top of SLList so that both push and pop are constant time. Which methods?", options: ["push=addLast, pop=removeFirst", "push=addFirst, pop=removeFirst", "push=addLast, pop=removeLast", "push=addFirst, pop=removeLast"], answer: 1, why: "Both operate at the front, where SLList is constant time." },

  /* ---------------- ArrayList ---------------- */
  { id: "al1", topic: "ArrayList", level: 2, kind: "type", q: "Capacity starts at 1 and doubles when full. After 16 addLast calls, how many total copy steps?", answer: "15", placeholder: "a number", why: "Copies happen at the 2nd (1), 3rd (2), 5th (4) and 9th (8) add: 1+2+4+8 = 15." },
  { id: "al2", topic: "ArrayList", level: 1, kind: "mcq", q: "Where is the last item of an AList with `size` items?", options: ["items[size]", "items[size - 1]", "items[size + 1]", "items[0]"], answer: 1, why: "Items occupy 0..size-1; items[size] is the next free slot." },
  { id: "al3", topic: "ArrayList", level: 2, kind: "mcq", q: "Why does removeLast set `items[size-1] = null`?", options: ["To make size correct", "So the removed object isn't kept alive by a stale reference", "To speed up get", "It's required for compilation"], answer: 1, why: "Garbage collection only frees objects with no references. The array cell would still refer to it." },
  { id: "al4", topic: "ArrayList", level: 2, kind: "mcq", q: "Cost of addFirst on an array list of n items?", options: ["Constant", "Grows with n: everything shifts right", "Grows with log n", "Always 1 copy"], answer: 1, why: "Every existing item has to move over by one." },
  { id: "al5", topic: "ArrayList", level: 2, kind: "mcq", q: "Cost of get(i) on an array list?", options: ["Constant", "Grows with i", "Grows with n", "Grows with size²"], answer: 0, why: "It's a single array read: items[i]." },
  { id: "al6", topic: "ArrayList", level: 3, kind: "mcq", q: "If capacity is 0 and resize does `newCap = capacity * 2`, what goes wrong?", options: ["Nothing", "0 × 2 = 0: the array never grows", "Integer overflow", "NullPointerException"], answer: 1, why: "Start with a positive capacity, or use max(1, 2 * capacity)." },
  { id: "al7", topic: "ArrayList", level: 3, kind: "mcq", q: "Why is doubling better than growing by +1?", options: ["It uses less memory", "Resizes become rare, so total copying is about 2n instead of about n²/2", "Arrays can only double", "It avoids null"], answer: 1, why: "With doubling, copy costs 1+2+4+… stay under 2n over n adds; +1 growth copies almost everything on every add." },
  { id: "al8", topic: "ArrayList", level: 2, kind: "mcq", q: "What happens if addLast forgets to resize when items is full?", code: `items[size] = x;\nsize++;`, options: ["Works fine", "ArrayIndexOutOfBoundsException", "NullPointerException", "The oldest item is overwritten"], answer: 1, why: "size == items.length, so items[size] is out of range." },

  /* ---------------- Invariants ---------------- */
  { id: "iv1", topic: "Invariants", level: 1, kind: "mcq", q: "When must a loop invariant be true?", options: ["At every line of the body", "Before the loop condition is tested, on entry and after each iteration", "Only after the loop", "Never; it's a comment"], answer: 1, why: "It may be temporarily broken inside the body, but must be restored before the next test." },
  { id: "iv2", topic: "Invariants", level: 2, kind: "mcq", q: "For `int s = 0, i = 0; while (i < n) { s += i; i++; }` which invariant holds at the top?", options: ["s = i", "s = 0 + 1 + … + (i − 1)", "s = n", "s = i²"], answer: 1, why: "At the top, i hasn't been added yet: s is the sum of 0..i-1 = i(i-1)/2." },
  { id: "iv3", topic: "Invariants", level: 2, kind: "mcq", q: "What termination measure proves `while (m > 0) { …; m -= 1; }` ends?", options: ["r", "m: it decreases by 1 each time and the loop stops at 0", "n", "m + r"], answer: 1, why: "A quantity that strictly decreases and is bounded below." },
  { id: "iv4", topic: "Invariants", level: 3, kind: "mcq", q: "Invariant: 0 ≤ i ≤ x. Loop condition: i < x. When the loop exits we know…", options: ["i < x", "i = x", "i = 0", "x = 0"], answer: 1, why: "!(i < x) gives i ≥ x, combined with i ≤ x gives i = x." },
  { id: "iv5", topic: "Invariants", level: 2, kind: "mcq", q: "Inside `if (x < 0) { … } else { … }`, what do you know in the else branch?", options: ["x < 0", "x >= 0", "nothing", "x == 0"], answer: 1, why: "The else branch runs exactly when the condition is false: !(x < 0), i.e. x ≥ 0." },

  /* ---------------- Running time ---------------- */
  { id: "rt1", topic: "Running time", level: 1, kind: "mcq", q: "Approximately how many times does the inner statement run?", code: `for (int i = 0; i < n; i++)\n    for (int j = 0; j < n; j++)\n        count++;`, options: ["n", "2n", "n²", "n log n"], answer: 2, why: "n × n iterations." },
  { id: "rt2", topic: "Running time", level: 2, kind: "mcq", q: "Approximately how many iterations?", code: `for (int i = 1; i < n; i *= 2)\n    count++;`, options: ["n", "n / 2", "about log₂ n", "n²"], answer: 2, why: "i doubles each time: 1, 2, 4, …; it takes about log₂ n steps to reach n." },
  { id: "rt3", topic: "Running time", level: 2, kind: "mcq", q: "The sum 0 + 2 + 4 + … + 2(n−1) computed by a loop over the n terms takes about how many steps? A closed formula takes how many?", options: ["n and n", "n and 1 (constant)", "n² and n", "1 and 1"], answer: 1, why: "The loop adds n terms. The formula n(n−1) needs a few arithmetic operations regardless of n." },
  { id: "rt4", topic: "Running time", level: 3, kind: "mcq", q: "Which grows fastest as n gets large?", options: ["100n", "n²", "n log n", "2n + 50"], answer: 1, why: "Quadratic beats linear and n log n eventually, whatever the constants." },
];

export const byTopic = (t: string) => QUESTIONS.filter((q) => q.topic === t);
